/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <pthread.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>
#include "bakery.h"


void bakery_prog_1(char *host)
{
	CLIENT *clnt;
    struct BAKERY *response;
    struct BAKERY bakery_proc_1_arg;
    clnt = clnt_create(host, BAKERY_PROG, BAKERY_VER, "udp");
    if (clnt == NULL) 
    {
        clnt_pcreateerror(host);
        exit(1);
    }
    srand(time(NULL));
    int interval = rand() % 3 + 1;
    sleep(interval);
    bakery_proc_1_arg.op = GET_NUMBER;
    response = bakery_proc_1(&bakery_proc_1_arg, clnt); 
    printf("Client pid = %d, number in queue = %d.\n", getpid(), response->num);
    if (response == (struct BAKERY *) NULL) 
        clnt_perror(clnt, "bakery_proc_1 failed");
    sleep(interval);
    bakery_proc_1_arg.op = GET_LETTER; 
    bakery_proc_1_arg.num = response->op; // индекс клиента в массивах
    bakery_proc_1_arg.pid = getpid();
    response = bakery_proc_1(&bakery_proc_1_arg, clnt);
    if (response == (struct BAKERY *) NULL) 
        clnt_perror(clnt, "bakery_proc_1 failed");
    printf("Client %d got %c (sleep = %d).\n", response->pid, response->letter, interval);
    clnt_destroy(clnt);
}


int main (int argc, char *argv[])
{
	setbuf(stdin, NULL);
    char *host;
    if (argc < 2) 
    {
        printf("Usage: %s server_host.\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    bakery_prog_1(host);
    exit(0);
}
